"""
Track revenue prediction library

This module provides functions for predicting revenue generated by music tracks
based on the number of reproductions (streams/plays).
"""

import numpy as np

def predict(quantity):
    """
    Predict track revenue using a baseline rule-of-thumb model.
    
    This function implements a simple linear relationship between the number
    of reproductions and revenue, using a fixed rate of 2€ per 1000 plays.
    This serves as the baseline model for comparison with future ML implementations.
    
    Parameters
    ----------
    quantity : float or array-like
        The number of reproductions/streams/plays for the track(s).
        Must be non-negative.
    
    Returns
    -------
    float or array-like
        Predicted revenue in euros.
    
    Notes
    -----
    The baseline formula is:
    
    $$\text{Revenue} = \frac{2.0 \times \text{Quantity}}{1000}$$
    
    This assumes a constant rate of 2€ per 1000 plays across all tracks,
    which is a simplification that doesn't account for factors such as:
    - Platform differences (Spotify, Apple Music, etc.)
    - Geographic location of listeners
    - Subscription type (premium vs. free tier)
    - Artist's contract terms
    
    Examples
    --------
    >>> predict(1000)
    2.0
    
    >>> predict(500000)
    1000.0
    
    >>> import numpy as np
    >>> predict(np.array([1000, 5000, 10000]))
    array([  2.,  10.,  20.])
    """

    # Convert to numpy array for uniform handling
    quantity_array = np.asarray(quantity)

    # Validate that all quantities are non-negative
    if np.any(quantity_array < 0):
        raise ValueError("'quantity' must be non-negative")

    return 2.0 * quantity_array / 1000.0
